### ISSUE TITLE
Compile source code

### ISSUE THREAD

**Issue by Fe7n** [chi-rei-den/TShock#10]
I’m not sure how to compile your source code, I’ve been trying to compile it in visual studio, without any success, I manually downloaded the terrariaServerAPI as it did not come with when I downloaded your source code, all I want to do is edit some settings in TShock.ConfigFile.cs.
Hope you can help me compile. Thanks a lot for your awesome work

**Comment by EMREOYUN** [comment]
Full compile help guide in README file, ServerAPI's guide is in Documents at solution file.
