### ISSUE TITLE
Not able to Compile!

### ISSUE THREAD

**Issue by Fe7n** [chi-rei-den/TShock#11]
!!!!!! PLEASE FILL IN THE TEMPLATE BELOW THANK YOU VERY MUCH !!!!!!

* TShock version: 
From your Source Code
* TShock build number (if known):
From your Source Code

#### Reproduction steps (if applicable)?
1. Build TShock.Modifications.ClientUUID
2. Build TShock.Modifications.Explosives
3. Rebuild TShock.Modifications.Bootstrapper
4. Problem: See Error Message!

#### Any stack traces or error messages (if known)?

1>------ Rebuild All started: Project: TShock.Modifications.Bootstrapper, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "OTAPI, Version=1.3.0.7, Culture=neutral, PublicKeyToken=null". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
1>  Consider app.config remapping of assembly "ILRepack, Culture=neutral, PublicKeyToken=c3e9373f1c31208e" from Version "2.0.13.0" [] to Version "2.1.0.0" [C:\Users\Feyn\source\repos\C1\TShock\TerrariaServerAPI\packages\ILRepack.Lib.2.1.0-beta1\lib\net40\ILRepack.dll] to solve conflict and get rid of warning.
1>  Consider app.config remapping of assembly "NuGet.Core, Culture=neutral, PublicKeyToken=31bf3856ad364e35" from Version "2.13.0.824" [] to Version "2.14.0.832" [C:\Users\Feyn\source\repos\C1\TShock\TerrariaServerAPI\packages\NuGet.Core.2.14.0\lib\net40-Client\NuGet.Core.dll] to solve conflict and get rid of warning.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2220,5): warning MSB3836: The explicit binding redirect on "ILRepack, Culture=neutral, PublicKeyToken=c3e9373f1c31208e" conflicts with an autogenerated binding redirect. Consider removing it from the application configuration file or disabling autogenerated binding redirects. The build will replace it with: "<bindingRedirect oldVersion="0.0.0.0-2.1.0.0" newVersion="2.1.0.0" xmlns="urn:schemas-microsoft-com:asm.v1" />".
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2220,5): warning MSB3836: The explicit binding redirect on "NuGet.Core, Culture=neutral, PublicKeyToken=31bf3856ad364e35" conflicts with an autogenerated binding redirect. Consider removing it from the application configuration file or disabling autogenerated binding redirects. The build will replace it with: "<bindingRedirect oldVersion="0.0.0.0-2.14.0.832" newVersion="2.14.0.832" xmlns="urn:schemas-microsoft-com:asm.v1" />".
1>  TShock.Modifications.Bootstrapper -> C:\Users\Feyn\source\repos\C1\TShock\TerrariaServerAPI\TShock.Modifications.Bootstrapper\bin\Debug\TShock.Modifications.Bootstrapper.exe
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========

#### Any screenshots?
No

#### Other information:
I have only used the files supplied in this source (I made a fork).
i have followed all steps provided in the README file,
i have no problem compiling the original TShock source.
I want to fix the bugs in this build, but theres no point if im not even able to compile it.
Please help me, it would mean alot!

Thanks for the great work!

**Comment by EMREOYUN** [comment]
This isn't offical TShock build and no support for this version. You will get no offical answers in there.

Is there is a way to add screenshot about your issue?

**Comment by Fe7n** [comment]
I moved on to other things :)

**Comment by EMREOYUN** [comment]
> I moved on to other things :)

Other things?

**Comment by Fe7n** [comment]
Making mods for xCom 2

**Comment by EMREOYUN** [comment]
> Making mods for xCom 2

Have fun :)
