### ISSUE TITLE
Hope authors add IPV6 support，Thanks

### ISSUE THREAD

**Issue by miwuzhise** [chi-rei-den/TShock#14]
* TShock version:
* TShock build number (if known):

#### Reproduction steps (if applicable)?

1. Some step
2. Some other step
3. Some bigger step
4. This is the problem

#### Any stack traces or error messages (if known)?

```
PUT SUPER LONG ERROR MESSAGES IN THE TICK MARKS
```

#### What plugins and what versions of those plugins are you running?

If I didn't provide any logs this issue, please close my issue immediately. I'm sorry for the inconvenience.

**Comment by sgkoishi** [comment]
A really late reply: 
I believe it supports IPv6 via a `-ip <address>` command line argument. Without `-ip` it will listen IPv4 any by default.
